# Generated by Django 5.0.1 on 2024-01-19 15:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_alter_order_total_price_alter_product_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateField(default=datetime.date(2001, 1, 21)),
        ),
    ]
