# Generated by Django 5.0.1 on 2024-01-20 15:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0003_alter_product_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_created',
            field=models.DateField(default=datetime.date(2024, 1, 20)),
        ),
    ]
