# Generated by Django 5.0.1 on 2024-01-23 15:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0004_order_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateField(default=datetime.date(2024, 1, 23)),
        ),
    ]
